AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
Layout/LineLength:
  Exclude:
    - 'spec/**/*_helper.rb'
  IgnoredPatterns: ['\A\s*#', '\A\s*".*"\Z']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Naming/VariableNumber:
  EnforcedStyle: snake_case
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
