name: test-and-deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libsqlite3
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - name: Setup ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bin/rails cop
      - name: Run rspec
        run: bin/rails spec
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      HEROKU_BASE_URL: "https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com"
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow the clone & push to heroku
        run: |
          cd $GITHUB_WORKSPACE
          git fetch --unshallow origin
          git push $HEROKU_URL master:master
        env:
          HEROKU_URL: "${{ env.HEROKU_BASE_URL }}/${{ secrets.HEROKU_APP_NAME }}.git"
